version: '3.7'
services:
    postgres:
        image: postgres:10-alpine
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - "${PWD}/db-data:/var/lib/postgresql/data"

    local-runner:
        image: amazon/mwaa-local:2.0.2
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
            - AIRFLOW_CONN_AWS_DEFAULT=aws://@/?role_arn=arn:aws:iam::815405947909:role/service-role/AmazonMWAA-Genzai-ZZCAiS
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ~/genzai/dags:/usr/local/airflow/dags
            - ${PWD}/plugins:/usr/local/airflow/plugins
            - ~/genzai/requirements/requirements.txt:/usr/local/airflow/dags/requirements.txt
        ports:
            - "8080:8080"
        command: local-runner
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
